name: Build Mac Executable

on:
  push:
    branches: [ "main" ]  # 当你推送代码到 main 分支时触发
  workflow_dispatch:      # 允许你手动点击按钮触发

jobs:
  build:
    runs-on: macos-latest  # 使用 GitHub 提供的 macOS 环境

    steps:
    - name: lan
      uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 使用 PyInstaller 打包
      run: |
        # --onefile: 打包成单个文件
        # --windowed: 如果是 GUI 程序，不显示终端窗口
        pyinstaller --onefile --windowed img_to_webp_tool.py

    - name: 上传成品
      uses: actions/upload-artifact@v4
      with:
        name: macos-executable
        path: dist/        # 打包后的文件存放在 dist 目录
